export const investmentFunds = [
  {
    id: "new-vine-short-duration-income-fund",
    name: "New Vine Short Duration Income Fund",
    type: "Private Credit Fund",
    strategy: "Private credit strategy focused on short-duration real estate transaction funding and capital deployment.",
    details: [
      "Short-duration focus",
      "Real estate transactional funding",
      "Asset-backed review process",
      "Operator-focused deployment",
    ],
    targetFocus: "Short-duration real estate transaction funding",
    structureType: "Managed private credit strategy",
    distributionStyle: "Subject to offering documents",
    status: "Accepting Investor Interest",
    cta: "Request Investor Access",
    visual: "SD",
  },
  {
    id: "new-vine-secured-yield-fund",
    name: "New Vine Secured Yield Fund",
    type: "Private Credit Fund",
    strategy: "Private credit strategy focused on real estate-backed second-position lending, gap funding, and structured collateral-based opportunities.",
    details: [
      "Structured private credit",
      "Second-position lending",
      "Gap funding opportunities",
      "Collateral-focused review",
    ],
    targetFocus: "Second-position and gap lending opportunities",
    structureType: "Managed private credit strategy",
    distributionStyle: "Subject to offering documents",
    status: "Investor Intake Open",
    cta: "Request Investor Access",
    visual: "SY",
  },
  {
    id: "new-vine-opportunistic-credit-fund",
    name: "New Vine Opportunistic Credit Fund",
    type: "Future Strategy",
    strategy: "Future private credit strategy focused on select real estate-backed capital opportunities reviewed through New Vine Capital's underwriting process.",
    details: [
      "Future private credit strategy",
      "Selective opportunity review",
      "Structured real estate capital",
      "Investor interest list",
    ],
    targetFocus: "Select real estate-backed capital opportunities",
    structureType: "Future managed strategy",
    distributionStyle: "To be determined by offering documents",
    status: "Coming Soon",
    cta: "Join Interest List",
    visual: "OC",
    comingSoon: true,
  },
];

export const dealOpportunities = [
  {
    id: "denver-multifamily-bridge-note",
    title: "Denver Multifamily Bridge Note",
    type: "Bridge Lending Opportunity",
    location: "Denver, Colorado",
    targetStructure: "Senior Secured Position",
    duration: "Estimated 12 Months",
    status: "Reviewing Investor Interest",
    cta: "Request Opportunity Overview",
    visual: "DM",
  },
  {
    id: "texas-transactional-funding-note",
    title: "Texas Transactional Funding Note",
    type: "Transactional Funding",
    location: "Dallas, Texas",
    targetStructure: "Short-Duration Capital Deployment",
    duration: "Estimated 30 Days",
    status: "Limited Availability",
    cta: "Request Opportunity Overview",
    visual: "TX",
  },
  {
    id: "arizona-gap-funding-note",
    title: "Arizona Gap Funding Note",
    type: "Second Position Lending",
    location: "Phoenix, Arizona",
    targetStructure: "Structured Gap Capital",
    duration: "Estimated 9 Months",
    status: "Preliminary Review Phase",
    cta: "Request Opportunity Overview",
    visual: "AZ",
  },
];

export const investorAccessSteps = [
  "Submit Investor Intake Form",
  "Schedule Investor Intake Call",
  "Complete Qualification Review",
  "Receive Access to Available Opportunities",
];

export const investorTrustPoints = [
  "Structured Review Process",
  "Private Investor Portal Access",
  "Asset-Backed Opportunity Focus",
  "Ongoing Investor Updates",
  "Relationship-Focused Communication",
];
