export const investmentFunds = [
  {
    id: "transactional-funding-fund",
    name: "Transactional Funding Fund",
    type: "Private Credit Fund",
    strategy: "Focused on short-duration transactional funding opportunities supporting real estate acquisition and closing strategies.",
    details: [
      "Short-duration focus",
      "Real estate transactional funding",
      "Asset-backed review process",
      "Operator-focused deployment",
    ],
    targetFocus: "Short-duration real estate transaction funding",
    structureType: "Managed private credit strategy",
    distributionStyle: "Subject to offering documents",
    status: "Accepting Investor Interest",
    cta: "Request Information",
    visual: "TF",
  },
  {
    id: "second-position-lending-fund",
    name: "Second Position Lending Fund",
    type: "Private Credit Fund",
    strategy: "Focused on structured second-position and gap lending opportunities backed by real estate collateral and defined capital structures.",
    details: [
      "Structured private credit",
      "Second-position lending",
      "Gap funding opportunities",
      "Collateral-focused review",
    ],
    targetFocus: "Second-position and gap lending opportunities",
    structureType: "Managed private credit strategy",
    distributionStyle: "Subject to offering documents",
    status: "Investor Intake Open",
    cta: "Request Information",
    visual: "SP",
  },
  {
    id: "opportunistic-credit-fund",
    name: "Opportunistic Credit Fund",
    type: "Future Strategy",
    strategy: "Planned future strategy focused on select opportunistic private credit and structured real estate capital opportunities.",
    details: [
      "Future private credit strategy",
      "Selective opportunity review",
      "Structured real estate capital",
      "Investor interest list",
    ],
    targetFocus: "Select opportunistic private credit opportunities",
    structureType: "Future managed strategy",
    distributionStyle: "To be determined by offering documents",
    status: "Coming Soon",
    cta: "Join Interest List",
    visual: "OC",
    comingSoon: true,
  },
];

export const dealOpportunities = [
  {
    id: "denver-multifamily-bridge-loan",
    title: "Denver Multifamily Bridge Loan",
    type: "Bridge Lending Opportunity",
    location: "Denver, Colorado",
    targetStructure: "Senior Secured Position",
    duration: "Estimated 12 Months",
    status: "Reviewing Investor Interest",
    cta: "Request Opportunity Overview",
    visual: "DM",
  },
  {
    id: "texas-transactional-funding-opportunity",
    title: "Texas Transactional Funding Opportunity",
    type: "Transactional Funding",
    location: "Dallas, Texas",
    targetStructure: "Short-Duration Capital Deployment",
    duration: "Estimated 30 Days",
    status: "Limited Availability",
    cta: "Request Opportunity Overview",
    visual: "TX",
  },
  {
    id: "arizona-gap-funding-opportunity",
    title: "Arizona Gap Funding Opportunity",
    type: "Second Position Lending",
    location: "Phoenix, Arizona",
    targetStructure: "Structured Gap Capital",
    duration: "Estimated 9 Months",
    status: "Preliminary Review Phase",
    cta: "Request Opportunity Overview",
    visual: "AZ",
  },
];

export const investorAccessSteps = [
  "Submit Investor Intake Form",
  "Schedule Investor Intake Call",
  "Complete Qualification Review",
  "Receive Access to Available Opportunities",
];

export const investorTrustPoints = [
  "Structured Review Process",
  "Private Investor Portal Access",
  "Asset-Backed Opportunity Focus",
  "Ongoing Investor Updates",
  "Relationship-Focused Communication",
];
