import Link from "next/link";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";
import { platformMetrics } from "../lib/investorPortalMockData";
import { siteLinks } from "../lib/siteLinks";

const publicPlatformMetrics = [
  ["Total Capital Deployed", "totalCapitalDeployed"],
  ["Transactions Funded", "transactionsFunded"],
  ["Active Investment Strategies", "activeStrategies"],
  ["Markets Served", "marketsServed"],
  ["Average Deal Duration", "averageDealDuration"],
  ["Capital Currently Allocated", "capitalCurrentlyAllocated"],
];

export default function Investors() {
  return (
    <div className="min-h-screen bg-[#050605] text-white">
      <SiteHeader />
      <main>
        <section className="nvc-page-bg px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl py-12"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d5ad62]">Investor Opportunities</p><h1 className="mt-5 max-w-5xl font-serif text-5xl leading-tight md:text-7xl">Private real estate debt exposure for passive capital partners.</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-white/75">Secured lending strategies structured around collateral, borrower experience, documented exits, and disciplined risk management.</p></div></section>
        <section className="bg-[#050605] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d5ad62]">Platform Activity</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-6xl">New Vine Capital Platform Activity</h2><p className="mt-5 text-lg leading-8 text-white/65">Historical activity across New Vine Capital's private real estate capital strategies. Figures are provided for informational purposes only and do not indicate future performance.</p></div><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{publicPlatformMetrics.map(([label, key]) => <article key={key} className="border border-white/10 bg-[#111613] p-4 shadow-xl shadow-black/10"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-[#d5ad62]">{label}</p><h3 className="mt-3 text-xl font-black leading-tight text-white md:text-2xl">{platformMetrics[key]}</h3></article>)}</div><p className="mt-4 max-w-5xl border-l-2 border-[#d5ad62]/70 bg-white/[0.025] px-3 py-2 text-[11px] leading-5 text-white/45">Platform activity is historical and informational only. Investment opportunities are subject to qualification, suitability review, allocation availability, and offering documents.</p></div></section>
        <section className="grid gap-8 bg-[#f4f1e9] px-5 py-24 text-[#050605] lg:grid-cols-[1fr_0.8fr] lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:contents"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#1f5b3f]">How It Works</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-6xl">Capital is matched to private lending opportunities.</h2><p className="mt-6 text-lg leading-8 text-[#53615a]">Qualified investors may participate through direct note opportunities, pooled strategies, or other structures depending on eligibility, availability, and offering terms.</p><ul className="mt-7 grid gap-3"><li className="border-l-4 border-[#d5ad62] bg-[#eee8da] p-4">Review investor profile and suitability</li><li className="border-l-4 border-[#d5ad62] bg-[#eee8da] p-4">Discuss available lending strategies</li><li className="border-l-4 border-[#d5ad62] bg-[#eee8da] p-4">Evaluate collateral, structure, and risk controls</li></ul></div><aside className="bg-white p-8 shadow-2xl shadow-black/10"><h3 className="text-xl font-black">Potential structures</h3><p className="mt-3 text-[#5e6962]">Direct trust deed or mortgage note participation, preferred return structures, pooled private debt vehicles, or other secured lending arrangements where appropriate.</p><h3 className="mt-8 text-xl font-black">Risk management</h3><p className="mt-3 text-[#5e6962]">Collateral review, conservative leverage analysis, title and lien diligence, exit validation, borrower review, and diversification discipline.</p></aside></div></section>
        <section className="bg-white px-5 py-24 text-[#050605] lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.85fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#1f5b3f]">Request Investor Information</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Start with a qualification and suitability review.</h2><p className="mt-5 text-lg leading-8 text-[#53615a]">New Vine Capital works with select private capital partners through a qualification and suitability review process. Investor inquiries are reviewed to understand experience, objectives, risk tolerance, eligibility, and fit for available private real estate debt opportunities.</p><div className="mt-6 border-l-4 border-[#d5ad62] bg-[#f4f1e9] p-5"><h3 className="text-xl font-black">Opportunities start as low as $100.</h3><p className="mt-2 text-sm leading-7 text-[#5e6962]">Minimum participation amounts vary by opportunity, structure, availability, and investor eligibility. All inquiries remain subject to review.</p></div><p className="mt-5 text-sm leading-7 text-[#5e6962]">Submitting an inquiry does not constitute an offer to invest, a solicitation to purchase securities, or a guarantee of eligibility. Any potential opportunity remains subject to verification, documentation, suitability review, and applicable legal requirements.</p></div><aside className="border border-black/10 bg-[#111613] p-7 text-white shadow-2xl shadow-black/10"><div className="border border-[#d5ad62]/40 bg-[#d5ad62]/10 p-6"><p className="text-sm font-black uppercase tracking-wide text-[#d5ad62]">Not approved yet?</p><h3 className="mt-3 text-3xl font-black leading-tight">Become an Approved Investor</h3><p className="mt-3 text-sm leading-6 text-white/65">Request investor information and begin New Vine Capital's qualification and suitability review process.</p><a href={siteLinks.jotformInvestorIntake} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex w-full justify-center bg-[#d5ad62] px-5 py-4 text-center text-xs font-black uppercase text-[#11100b] transition hover:bg-[#f0d99a] sm:w-auto">Become an Approved Investor</a><p className="mt-4 text-xs leading-5 text-white/45">Submitting an inquiry does not guarantee eligibility or constitute an offer to invest.</p></div></aside></div></section>
        <section className="bg-[#123827] px-5 py-20 text-white lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d5ad62]">Investor Intake Call</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Ready to Speak With New Vine Capital?</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-white/70">Schedule an Investor Intake Call to discuss your objectives, qualification, and available private real estate capital strategies.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link href={siteLinks.investorBookCall} className="bg-[#d5ad62] px-7 py-4 text-center text-xs font-black uppercase text-[#11100b] transition hover:bg-[#f0d99a]">Book Investor Intake Call</Link><a href={siteLinks.jotformInvestorIntake} target="_blank" rel="noopener noreferrer" className="border border-[#d5ad62]/70 px-7 py-4 text-center text-xs font-black uppercase text-[#d5ad62] transition hover:bg-[#d5ad62] hover:text-[#11100b]">Complete Investor Intake Form</a></div></div></section>
        <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d5ad62]">FAQ</p><h2 className="mt-4 max-w-4xl font-serif text-4xl leading-tight md:text-6xl">Questions passive investors usually ask.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Is this passive?", "Structures may be designed for passive exposure, with New Vine Capital managing origination and borrower communication."], ["What secures the capital?", "Private real estate debt is generally secured by real estate collateral, subject to final structure and diligence."], ["Who can invest?", "Eligibility depends on offering structure, investor qualification, regulatory requirements, and available opportunities."]].map(([t,c]) => <article key={t} className="border border-white/10 bg-[#111613] p-7"><h3 className="text-xl font-black">{t}</h3><p className="mt-4 text-white/60">{c}</p></article>)}</div></section>
      </main>
      <SiteFooter />
    </div>
  );
}
