import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

const INVESTOR_INQUIRY_URL = "https://form.jotform.com/261394894022057";

export default function Investors() {
  return (
    <div className="min-h-screen bg-[#050605] text-white">
      <SiteHeader />
      <main>
        <section className="nvc-page-bg px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl py-12"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d5ad62]">Investor Opportunities</p><h1 className="mt-5 max-w-5xl font-serif text-5xl leading-tight md:text-7xl">Private real estate debt exposure for passive capital partners.</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-white/75">Secured lending strategies structured around collateral, borrower experience, documented exits, and disciplined risk management.</p></div></section>
        <section className="grid gap-8 bg-[#f4f1e9] px-5 py-24 text-[#050605] lg:grid-cols-[1fr_0.8fr] lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:contents"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#1f5b3f]">How It Works</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-6xl">Capital is matched to private lending opportunities.</h2><p className="mt-6 text-lg leading-8 text-[#53615a]">Qualified investors may participate through direct note opportunities, pooled strategies, or other structures depending on eligibility, availability, and offering terms.</p><ul className="mt-7 grid gap-3"><li className="border-l-4 border-[#d5ad62] bg-[#eee8da] p-4">Review investor profile and suitability</li><li className="border-l-4 border-[#d5ad62] bg-[#eee8da] p-4">Discuss available lending strategies</li><li className="border-l-4 border-[#d5ad62] bg-[#eee8da] p-4">Evaluate collateral, structure, and risk controls</li></ul></div><aside className="bg-white p-8 shadow-2xl shadow-black/10"><h3 className="text-xl font-black">Potential structures</h3><p className="mt-3 text-[#5e6962]">Direct trust deed or mortgage note participation, preferred return structures, pooled private debt vehicles, or other secured lending arrangements where appropriate.</p><h3 className="mt-8 text-xl font-black">Risk management</h3><p className="mt-3 text-[#5e6962]">Collateral review, conservative leverage analysis, title and lien diligence, exit validation, borrower review, and diversification discipline.</p></aside></div></section>
        <section className="bg-white px-5 py-24 text-[#050605] lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.85fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#1f5b3f]">Request Investor Information</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Start with a qualification and suitability review.</h2><p className="mt-5 text-lg leading-8 text-[#53615a]">New Vine Capital works with select private capital partners through a qualification and suitability review process. Investor inquiries are reviewed to understand experience, objectives, risk tolerance, eligibility, and fit for available private real estate debt opportunities.</p><p className="mt-5 text-sm leading-7 text-[#5e6962]">Submitting an inquiry does not constitute an offer to invest, a solicitation to purchase securities, or a guarantee of eligibility. Any potential opportunity remains subject to verification, documentation, suitability review, and applicable legal requirements.</p></div><aside className="border border-black/10 bg-[#f4f1e9] p-7 shadow-2xl shadow-black/10"><div className="border-l-4 border-[#d5ad62] bg-white p-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#1f5b3f]">New Vine Capital Investor Inquiry</p><div className="mt-6 grid min-h-[320px] place-items-center border border-dashed border-[#d5ad62]/70 bg-[#fbf8f0] p-8 text-center"><div><h3 className="text-2xl font-black">Investor Inquiry Form</h3><p className="mt-3 text-[#5e6962]">Use the New Vine Capital Investor Inquiry form to request information and begin the qualification review process.</p><a href={INVESTOR_INQUIRY_URL} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex bg-[#d5ad62] px-6 py-4 text-xs font-black uppercase text-[#11100b]">Submit Investor Inquiry</a></div></div></div></aside></div></section>
        <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d5ad62]">FAQ</p><h2 className="mt-4 max-w-4xl font-serif text-4xl leading-tight md:text-6xl">Questions passive investors usually ask.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Is this passive?", "Structures may be designed for passive exposure, with New Vine Capital managing origination and borrower communication."], ["What secures the capital?", "Private real estate debt is generally secured by real estate collateral, subject to final structure and diligence."], ["Who can invest?", "Eligibility depends on offering structure, investor qualification, regulatory requirements, and available opportunities."]].map(([t,c]) => <article key={t} className="border border-white/10 bg-[#111613] p-7"><h3 className="text-xl font-black">{t}</h3><p className="mt-4 text-white/60">{c}</p></article>)}</div></section>
      </main>
      <SiteFooter />
    </div>
  );
}
